---
- hosts: all
  become: true
  connection: local
  tasks:
    - name: Pull images Docker légères
      community.docker.docker_image:
        name: "{{ item }}"
        source: pull
      loop:
        - node:20-alpine
        - python:3.11-alpine
        - nginx:alpine
        - mysql:8.0-oraclelinux8
        - redis:alpine